export const APPLICATION_INITIALIZE_ROUTES = 'application:initialize-routes'
export const APPLICATION_INITIALIZE_CONFIG = 'application:initialize-config'
export const APPLICATION_PREPARE_CONFIG = 'application:prepare-config'
export const APPLICATION_SAVE_CONFIG = 'application:save-config'
export const APPLICATION_INITIALIZE_APP = 'application:initialize-app'
export const APPLICATION_INITIALIZE_PLUGINS = 'application:initialize-plugins'
